const ExperinceData = [
  {
    company: '',
    location: '',
    roles: [
      // {
      //   title: 'Web Devoloper',
      //   startDate: 'January 2024',
      //   endDate: 'Present',
      //   duration: '4 mos',
      //   workMode: 'On-site',
      //   description: [
      //     'Developed scalable applications using TypeScript, React, and Next.js.',
      //     'Worked with various databases like Postgres, MongoDB, and Redis.',
      //     'Hands-on with AWS and Azure services (S3, EC2, Lambda).',
      //     'Experience with streaming data.',
      //     'Expertise in deployment and CI/CD processes.',
      //     'Log monitoring and alerting using Elasticsearch.',
      //   ],
      //   skills: [
      //     'TypeScript',
      //     'React',
      //     'Next',
      //     'Postgres',
      //     'MongoDB',
      //     'MySQL',
      //     'Redis',
      //     'Docker',
      //     'AWS',
      //     'Azure',
      //     'Elasticsearch',
      //     'Nest',
      //     'Express',
      //     'Node',
      //     'REST',
      //     'Socket.io',
      //   ],
      // },
      // {
      //   title: 'Associate Software Engineer',
      //   startDate: 'May 2022',
      //   endDate: 'January 2024',
      //   duration: '1 yr 9 mos',
      //   workMode: 'On-site',
      //   description: [
      //     'Proficiency in Agile development methodologies.',
      //     'Developed robust applications using Nest.js and Next.js.',
      //     'Experience with message queuing and Elasticsearch.',
      //     'Hands-on with AWS and Azure services (S3, EC2, Lambda).',
      //     'Expertise in deployment and CI/CD processes.',
      //   ],
      //   skills: [
      //     'TypeScript',
      //     'Python (Programming Language)',
      //     'React',
      //     'Next',
      //     'Postgres',
      //     'MongoDB',
      //     'MySQL',
      //     'Redis',
      //     'Docker',
      //     'AWS',
      //     'Azure',
      //     'Elasticsearch',
      //     'Nest',
      //     'Express',
      //     'Node',
      //     'REST',
      //     'Socket.io',
      //   ],
      // },
      {
        title: '',
        startDate: '',
        endDate: '',
        workMode: '',
        duration: '',
        description: [''
        ],
        skills: [''],
      },
    ],
  },
];

export default ExperinceData;
